name: Android CD

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # set up android platform toosl
      - uses: malinskiy/action-android/install-sdk@release/0.1.0
      - run: sdkmanager platform-tools
      - name: Build packages
        run: ./gradlew --no-daemon clean build

      - uses: Tlaster/android-sign@v1.2.2
        name: Sign app APK
        with:
          releaseDirectory: |
            ./app/build/outputs/apk/iPlayer/release/
            ./app/build/outputs/apk/all4/release/
            ./app/build/outputs/apk/itvHub/release/
            ./app/build/outputs/apk/bbcSounds/release/
            ./app/build/outputs/apk/uktvPlay/release/
            ./app/build/outputs/apk/britbox/release/
            ./app/build/outputs/apk/my5/release/
            ./app/build/outputs/apk/stv/release/
          signingKeyBase64: ${{ secrets.ANDROID_KEY_BASE64 }}
          output: build/signed
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: 28.0.3

      - run: |
          set -x
          assets=()
          for asset in ./build/signed/*.apk; do
            signedAsset="${asset//-unsigned/}"
            mv "$asset" $signedAsset
            assets+=($signedAsset)
          done
          tag_name="${GITHUB_REF##*/}"
          gh release create "$tag_name" "${assets[@]}" --title "$tag_name" --notes "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
